/*****************************************************
*          Nome: Script_LojaDoce         
*   Observações: Script de criação da base de dados
*   Dt. Criação: 04/04/2024
* Dt. Alteração:
*    Criada por: D4rkFire
******************************************************/

PRINT N'Beginning of the Data Base Creation...';
GO

PRINT N'Creating table Usuário...[dbo.TB_USUARIO]';
GO
CREATE TABLE [dbo].[TB_USUARIO] 
(
[I_COD_USUARIO] INT IDENTITY (1, 1) NOT NULL,
[S_NM_USUARIO] VARCHAR (40) NOT NULL,
[S_UNM_USUARIO] VARCHAR (40) NOT NULL,
[S_PW_USUARIO] VARCHAR (32) NOT NULL, 
PRIMARY KEY CLUSTERED ([I_COD_USUARIO] ASC)
);


PRINT N'Creating table Cliente...[dbo.TB_CLIENTE]';
GO
CREATE TABLE [dbo].[TB_CLIENTE] 
(
[I_COD_CLIENTE] INT IDENTITY (1, 1) NOT NULL,
[S_NM_CLIENTE] VARCHAR (40) NOT NULL,
[S_TEL_CLIENTE] VARCHAR (11) NOT NULL,
[S_EMAIL_CLIENTE] VARCHAR (32) NOT NULL,
[S_CPF_CLIENTE] VARCHAR (11) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_CLIENTE] ASC)
);


PRINT N'Creating table Fornecedor...[dbo.TB_FORNECEDOR]';
GO
CREATE TABLE [dbo].[TB_FORNECEDOR] 
(
[I_COD_FORNECEDOR] INT IDENTITY (1, 1) NOT NULL,
[S_NM_FORNECEDOR] VARCHAR (35) NOT NULL,
[S_TEL_FORNECEDOR] VARCHAR (11) NOT NULL,
[S_END_FORNECEDOR] VARCHAR (40) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_FORNECEDOR] ASC)
);


PRINT N'Creating table Fabricante...[dbo.TB_FABRICANTE]';
GO
CREATE TABLE [dbo].[TB_FABRICANTE] 
(
[I_COD_FABRICANTE] INT IDENTITY (1, 1) NOT NULL,
[S_NM_FABRICANTE] VARCHAR (35) NOT NULL,
[S_TEL_FABRICANTE] VARCHAR (11) NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_FABRICANTE] ASC)
);


PRINT N'Creating table Produto...[dbo.TB_PRODUTO]';
GO
CREATE TABLE [dbo].[TB_PRODUTO] 
(
[I_COD_PRODUTO] INT IDENTITY (1, 1) NOT NULL,
[I_COD_FORNECEDOR] INT NOT NULL,
[I_COD_FABRICANTE] INT NOT NULL,
[S_NM_PRODUTO] VARCHAR (30) NOT NULL,
[I_VLR_PRODUTO] INT NOT NULL,
[I_VLRUNIT_PRODUTO] INT NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_PRODUTO] ASC),
FOREIGN KEY ([I_COD_FORNECEDOR]) REFERENCES [dbo].[TB_FORNECEDOR] ([I_COD_FORNECEDOR]),
FOREIGN KEY ([I_COD_FABRICANTE]) REFERENCES [dbo].[TB_FABRICANTE] ([I_COD_FABRICANTE])
);


PRINT N'Creating table Itens...[dbo.TB_ITENS]';
GO
CREATE TABLE [dbo].[TB_ITENS] 
(
[I_COD_ITENS] INT IDENTITY (1, 1) NOT NULL,
[I_COD_PRODUTO] INT NOT NULL,
[I_QTDE_ITENS] INT NOT NULL,
[D_VLRSUB_ITENS] DECIMAL NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_ITENS] ASC),
FOREIGN KEY ([I_COD_PRODUTO]) REFERENCES [dbo].[TB_PRODUTO] ([I_COD_PRODUTO])
);


PRINT N'Creating table Pedido...[dbo.TB_PEDIDO]';
GO
CREATE TABLE [dbo].[TB_PEDIDO] 
(
[I_COD_PEDIDO] INT IDENTITY (1, 1) NOT NULL,
[I_COD_CLIENTE] INT NOT NULL,
[I_COD_ITENS] INT NOT NULL,
[I_VLRTOT_PEDIDO] INT NOT NULL,
PRIMARY KEY CLUSTERED ([I_COD_PEDIDO] ASC),
FOREIGN KEY ([I_COD_CLIENTE]) REFERENCES [dbo].[TB_CLIENTE] ([I_COD_CLIENTE]),
FOREIGN KEY ([I_COD_ITENS]) REFERENCES [dbo].[TB_ITENS] ([I_COD_ITENS])
);